[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "robocek"
version = "0.1.1"
description = "ROBOCEK Embedded Robotics Development Platform"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "rich",
    "platformio",
    "pyserial",
    "pyyaml"
]

[project.scripts]
robocek = "robocek.cli:app"

[tool.setuptools]
packages = ["robocek"]

[tool.setuptools.package-data]
robocek = [
    "boards/**/*",
    "sdk/**/*",
    "templates/**/*",
    "examples/**/*"
]