from pathlib import Path

from .board import Board


def generate_motor_config(board: Board, output: Path):
    motor = board.motor

    left = motor["left"]
    right = motor["right"]

    content = f"""#pragma once

// ========================================
// Generated by ROBOCEK Platform
// Board: {board.name}
// ========================================

#define RC_MOTOR_STBY {motor["standby"]}

// Left motor
#define RC_LEFT_PWM {left["pwm"]}
#define RC_LEFT_IN1 {left["in1"]}
#define RC_LEFT_IN2 {left["in2"]}

// Right motor
#define RC_RIGHT_PWM {right["pwm"]}
#define RC_RIGHT_IN1 {right["in1"]}
#define RC_RIGHT_IN2 {right["in2"]}
"""

    output.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    output.write_text(
        content,
        encoding="utf-8"
    )


def generate_project_config(
    project_dir: Path,
    board: Board
):
    """Generate all configuration files for a ROBOCEK project."""

    output = (
        project_dir
        / "generated"
        / "robocek_config.h"
    )

    generate_motor_config(
        board,
        output
    )
    generate_line_sensor_config(
        board,
        output
    )
    generate_ultrasonic_config(
        board,
        output
    )

    return output

def generate_line_sensor_config(
    board: Board,
    output: Path
):
    sensor = board.data.get("line_sensor")

    if not sensor:
        return

    left = sensor["left"]
    right = sensor["right"]

    active = sensor.get("active", "HIGH").upper()

    if active not in ("LOW", "HIGH"):
        raise ValueError(
            "line_sensor.active must be LOW or HIGH"
        )

    content = f"""
// ========================================
// Line Sensor Configuration
// ========================================

#define RC_LINE_SENSOR_LEFT {left["pin"]}
#define RC_LINE_SENSOR_RIGHT {right["pin"]}
#define RC_LINE_SENSOR_ACTIVE {active}
"""

    with output.open(
        "a",
        encoding="utf-8"
    ) as file:

        file.write(content)

def generate_ultrasonic_config(
    board: Board,
    output: Path
):
    ultrasonic = board.data.get("ultrasonic_sensor")
    if not ultrasonic:
        return
    left = ultrasonic["left"]
    right = ultrasonic["right"]

    content = f"""
// ========================================
// Ultrasonic Sensor Configuration
// ========================================
#define RC_ULTRASONIC_LEFT_TRIGGER {left["trigger"]}
#define RC_ULTRASONIC_LEFT_ECHO {left["echo"]}
#define RC_ULTRASONIC_RIGHT_TRIGGER {right["trigger"]}
#define RC_ULTRASONIC_RIGHT_ECHO {right["echo"]}
"""
    with output.open(
        "a",
        encoding="utf-8"
    ) as file:
        file.write(content)