from pathlib import Path

from .board import Board


def generate_motor_config(board: Board, output: Path):
    motor = board.motor

    left = motor["left"]
    right = motor["right"]

    content = f"""#pragma once

// ========================================
// Generated by ROBOCEK Platform
// Board: {board.name}
// ========================================

#define RC_MOTOR_STBY {motor["standby"]}

// Left motor
#define RC_LEFT_PWM {left["pwm"]}
#define RC_LEFT_IN1 {left["in1"]}
#define RC_LEFT_IN2 {left["in2"]}

// Right motor
#define RC_RIGHT_PWM {right["pwm"]}
#define RC_RIGHT_IN1 {right["in1"]}
#define RC_RIGHT_IN2 {right["in2"]}
"""

    output.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    output.write_text(
        content,
        encoding="utf-8"
    )


def generate_project_config(
    project_dir: Path,
    board: Board
):
    """Generate all configuration files for a ROBOCEK project."""

    output = (
        project_dir
        / "generated"
        / "robocek_config.h"
    )

    generate_motor_config(
        board,
        output
    )
    generate_line_sensor_config(
        board,
        output
    )

    return output

def generate_line_sensor_config(
    board: Board,
    output: Path
):
    sensor = board.data.get("line_sensor")

    if not sensor:
        return

    left = sensor["left"]
    right = sensor["right"]

    content = f"""
// ========================================
// Line Sensor Configuration
// ========================================

#define RC_LINE_SENSOR_LEFT {left["pin"]}
#define RC_LINE_SENSOR_RIGHT {right["pin"]}
"""

    with output.open(
        "a",
        encoding="utf-8"
    ) as file:

        file.write(content)